install.packages("readxl")
install.packages("tidyverse")
install.packages("readr")
install.packages("ggplot2")
library(tidyverse)
library(readr)
library(readxl)
library(ggplot2)
logs <- read_csv("beehive.csv")
View(logs)
hist(logs)
hist(logs$weight)
hist(logs$temp1)
hist(logs$temp2)
hist(logs$hum1)
ggplot(logs)+geom_point(aes(x=weight,y=hum2))