View(mtcars)
str(cor(mtcars))
cor(mtcars$mpg, mtcars$hp, method = "spearman")
require(corrgram)
corrgram(mtcars)
require(ggplot2)
ggplot(mtcars)+geom_point(aes(x=disp,y=wt))
ggplot(mtcars)+geom_point(aes(x=disp,y=wt, col=as.factor(cyl)))
ggplot(mtcars)+geom_point(aes(x=disp,y=wt, col=cyl))
ggplot(mtcars)+geom_point(aes(x=disp,y=wt, col=as.factor(cyl), size=mpg))
